name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
      - name: Zip file into a specific archive
        run: zip -j build.zip target/*jar
      
      - uses: actions/upload-artifact@v2
        with:
          name: Release
          path: target/*jar
      
      - run: rm -rf target

      - run: rm -rf .git

      - uses: actions/upload-artifact@v2
        with:
          name: source
          path: ./


