name: Java CI - nightly builds
on:
  schedule:
    - cron:  '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        
      
      - uses: actions/upload-artifact@v2
        with:
          name: nightly
          path: target/*jar
      
#      - run: rm -rf target
      
#      - run: rm -rf .git
      
#      - uses: actions/upload-artifact@v2
#        with:
#          name: source
#          path: ./
